services:
  travellan_api:
    image: registry.grzegorz-pietrzak.pl/travellan/travellan-api
    restart: always
    ports:
      - '3001:3001'
    expose:
      - '3001'
    networks:
      - travellan
